#!/bin/bash

SCRIPT_FILE="$(readlink -f "$0" 2>/dev/null || readlink "$0" 2>/dev/null || echo "$0")"
SCRIPT_DIR="${SCRIPT_FILE%/*}"

BUILD_ENVIRONMENT="$1"

FORCE=1
SYNTAX="default"
EXTENSION="wiki"
OUTPUTDIR="$SCRIPT_DIR/docs"
CSS_FILE="-"
TEMPLATE_PATH="$SCRIPT_DIR/templates"
TEMPLATE_DEFAULT="default"
TEMPLATE_EXT="-"
ROOT_PATH="-"

if [ $BUILD_ENVIRONMENT == "prod" ]; then
    WEBROOT="https://TMDeal.github.io"
else
    WEBROOT="http://127.0.0.1:8080"
fi

echo "[!] Copying assets into $OUTPUTDIR"

echo "[.] Copying images..."
cp -r "$SCRIPT_DIR"/images "$OUTPUTDIR"/images
echo "[.] Copying css..."
cp -r "$SCRIPT_DIR"/css "$OUTPUTDIR"/css

echo -e "[O] Done! Assets have been copied\n"

echo "[!] Converting vimwiki files"

for INPUT in $(find $SCRIPT_DIR -type f -name "*.wiki"); do
    INPUT_RELATIVE=$(realpath --relative-to "$SCRIPT_DIR" $INPUT)
    echo "[.] Converting $INPUT_RELATIVE to html"

    REAL_OUTPUTDIR="$OUTPUTDIR"/$(realpath --relative-to "$SCRIPT_DIR" $INPUT | xargs dirname)
    mkdir -p $REAL_OUTPUTDIR

    "$SCRIPT_DIR"/wiki2html \
        "$FORCE" \
        "$SYNTAX" \
        "$EXTENSION" \
        "$REAL_OUTPUTDIR" \
        "$INPUT" \
        "$CSS_FILE" \
        "$TEMPLATE_PATH" \
        "$TEMPLATE_DEFAULT" \
        "$TEMPLATE_EXT" \
        "$ROOT_PATH" \
        "$WEBROOT"
done

echo "[O] Done! html files are located in $OUTPUTDIR"
