baseURL: https://TMDeal.github.io
languageCode: en-us
title: TMDeal Pages
theme: PaperMod
  author: "Trent Deal"

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  TocOpen: false
  searchHidden: false
  disableHLJS: false
  disableShare: false

  profileMode:
    enabled: true
    title: TMDeal Home
    subtitle: Place to post my things
    imageUrl: "images/profile.png"
    imageTitle: profile
    buttons:
      - name: HackTheBox
        url: /htb
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    ignoreLocation: true
    threshold: 0
    minMatchCharLength: 1
    keys: ["title"]

menu:
  main:
    - identifier: Search
      name: Search
      url: /search/
      weight: 10
    - identifier: Archives
      name: Archives
      url: /archives/
      weight: 20
    - identifier: Categories
      name: Categories
      url: /categories/
      weight: 30
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 40

outputs:
  home:
    - HTML
    - RSS
    - JSON
