baseURL: https://TMDeal.github.io
languageCode: en-us
title: TMDeal
paginate: 5
theme: PaperMod

params:
  title: "TMDeal"
  description: "Github pages for TMDeal"
  keywords: [ Blog, Hacking, Portfolio ]
  author: "Trent Deal"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  TocOpen: false
  searchHidden: false
  disableHLJS: false
  disableShare: false

  assets:
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

  profileMode:
    enabled: true
    title: TMDeal Home
    subtitle: Place to post my things
    imageUrl: "images/profile.png"
    imageTitle: profile
    buttons:
      - name: HackTheBox
        url: /htb

  socialIcons:
    - name: github
      url: https://github.com/TMDeal/
    # - name: twitter
    #   url: https://twitter.com/TMDealio

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    ignoreLocation: true
    threshold: 0
    minMatchCharLength: 1
    keys: ["title"]

menu:
  main:
    - identifier: Search
      name: Search
      url: /search/
      weight: 10
    - identifier: Archives
      name: Archives
      url: /archives/
      weight: 20
    - identifier: Categories
      name: Categories
      url: /categories/
      weight: 30
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 40

outputs:
  home:
    - HTML
    - RSS
    - JSON
