#!/bin/bash

FORCE="$1"
SYNTAX="$2"
EXTENSION="$3"
OUTPUTDIR="$4"
INPUT="$5"
TEMPLATE_PATH="$7"
TEMPLATE_DEFAULT="$8"

if [ "${11}" == "-" ]; then
    WEBROOT="http://127.0.0.1:8080"
else
    WEBROOT="${11}"
fi

SCRIPT_FILE="$(readlink -f "$0" 2>/dev/null || readlink "$0" 2>/dev/null || echo "$0")"
SCRIPT_DIR="${SCRIPT_FILE%/*}"

FORCEFLAG=

[ $FORCE -eq 0 ] || { FORCEFLAG="-f"; };
[ $SYNTAX = "default" ] || { echo "Error: Unsupported syntax"; exit -2; };

OUTPUT="$OUTPUTDIR"/$(basename "$INPUT" .$EXTENSION).html

TITLE=$(basename "$INPUT" .$EXTENSION)
DATE=$(date +"%Y-%m-%d")

METADATA_PATH="$SCRIPT_DIR"/metadata
METADATA_INPUT_RELATIVE=$(realpath --relative-to "$SCRIPT_DIR" "$INPUT" | cut -f 1 -d ".").yml
METADATA="$METADATA_PATH/$METADATA_INPUT_RELATIVE"

DATA_PATH="$SCRIPT_DIR"/data
FILTERS_PATH="$DATA_PATH"/filters

DEFAULTS=$(cat <<- EOF
template: $TEMPLATE_DEFAULT
metadata:
    webroot: $WEBROOT
    title: ${TITLE^}
    created_at: $DATE
    last_updated: $DATE
EOF
)

if [ ! -f "$METADATA" ]; then
    mkdir -p "$METADATA_PATH/$(dirname $METADATA_INPUT_RELATIVE)"
    printf "$DEFAULTS" > "$METADATA"
fi

sed -i -E "s,(.*webroot:).*,\1 $WEBROOT,g" "$METADATA"
sed -i -E "s/(.*last_updated:).*/\1 $DATE/g" "$METADATA"

pandoc -f vimwiki -t html $INPUT \
    --output "$OUTPUT" \
    --data-dir "$DATA_PATH" \
    --defaults "$METADATA" \
    --lua-filter="$FILTERS_PATH"/fix_images.lua
