#!/bin/bash

# vimwiki expects these arguments in specific places, so we will make sure they
# are where vimwiki expects them to be
FORCE="$1"
SYNTAX="$2"
EXTENSION="$3"
OUTPUTDIR="$4"
INPUT="$5"
TEMPLATE_PATH="$7"
TEMPLATE_DEFAULT="$8"

# vimwiki sets an unset argument as a "-" instead of "". Was a little annoying
if [ "${11}" == "-" ]; then
    WEBROOT="http://127.0.0.1:8888"
else
    WEBROOT="${11}"
fi

SCRIPT_FILE="$(readlink -f "$0" 2>/dev/null || readlink "$0" 2>/dev/null || echo "$0")"
SCRIPT_DIR="${SCRIPT_FILE%/*}"

FORCEFLAG=

[ $FORCE -eq 0 ] || { FORCEFLAG="-f"; };
[ $SYNTAX = "default" ] || { echo "Error: Unsupported syntax"; exit -2; };

OUTPUT="$OUTPUTDIR"/$(basename "$INPUT" .$EXTENSION).html

TITLE=$(basename "$INPUT" .$EXTENSION)
DATE=$(date +"%Y-%m-%d")

# path to generated metadata files. 
METADATA_PATH="$SCRIPT_DIR"/metadata
METADATA_INPUT_RELATIVE=$(realpath --relative-to "$SCRIPT_DIR" "$INPUT" | cut -f 1 -d ".").yml
METADATA="$METADATA_PATH/$METADATA_INPUT_RELATIVE"

# Path to local pandoc data files
DATA_PATH="$SCRIPT_DIR"/data
FILTERS_PATH="$DATA_PATH"/filters

DEFAULTS=$(cat <<- EOF
template: $TEMPLATE_DEFAULT
metadata:
    webroot: $WEBROOT
    title: ${TITLE^}
    created_at: $DATE
    last_updated: $DATE
EOF
)

# Always create a metadata file if an associated file does not already have
# one. This will be set to the defaults defined in $DEFAULTS
if [ ! -f "$METADATA" ]; then
    mkdir -p "$METADATA_PATH/$(dirname $METADATA_INPUT_RELATIVE)"
    printf "$DEFAULTS" > "$METADATA"
fi

# Always update the web root since it may change between development and production
sed -i -E "s,(.*webroot:).*,\1 $WEBROOT,g" "$METADATA"
# Set last updated to be equal to the date this file was last rebuilt
# TODO: a rebuild may not always mean the file gets updated, rethink this
sed -i -E "s/(.*last_updated:).*/\1 $DATE/g" "$METADATA"

pandoc -f vimwiki -t html $INPUT \
    --output "$OUTPUT" \
    --data-dir "$DATA_PATH" \
    --defaults "$METADATA" \
    --lua-filter="$FILTERS_PATH"/fix_images.lua
