#!/bin/bash

SCRIPT_FILE="$(readlink -f "$0" 2>/dev/null || readlink "$0" 2>/dev/null || echo "$0")"
SCRIPT_DIR="${SCRIPT_FILE%/*}"
ROOT_DIR=$(realpath "$SCRIPT_DIR/..")

INPUT="$ROOT_DIR/$1"
OUTPUT="$ROOT_DIR/$2"
DATA_DIR="$ROOT_DIR/$3"
META_FILE="$ROOT_DIR/$4"

FILTERS="$DATA_DIR/filters"

pandoc -f vimwiki -t html $INPUT \
    --output $OUTPUT \
    --data-dir $DATA_DIR \
    --defaults "$META_FILE" \
    --lua-filter $FILTERS/fix_images.lua
