#!/bin/bash

SCRIPT_FILE="$(readlink -f "$0" 2>/dev/null || readlink "$0" 2>/dev/null || echo "$0")"
SCRIPT_DIR="${SCRIPT_FILE%/*}"
ROOT_DIR=$(realpath "$SCRIPT_DIR/..")

META_FILE="$ROOT_DIR/$1"
TEMPLATE="default"
TITLE=$(basename $META_FILE .yml)
DATE=$(date +"%Y-%m-%d")

DEFAULTS=$(cat <<- EOF
template: $TEMPLATE
metadata:
    title: ${TITLE^}
    created_at: $DATE
    last_updated: $DATE
EOF
)

# Always create a metadata file if an associated file does not already have
# one. This will be set to the defaults defined in $DEFAULTS
if [ ! -f "$META_FILE" ]; then
    mkdir -p $(dirname "$META_FILE")
    printf "$DEFAULTS" > "$META_FILE"
fi

# Set last updated to be equal to the date this file was last rebuilt
sed -i -E "s/(.*last_updated:).*/\1 $DATE/g" "$META_FILE"
